- id: '1564517226706'
  alias: Alle lichten uit om 2 uur s'nachts
  trigger:
  - at: 02:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: group.all_lights_switches
    service: homeassistant.turn_off
- id: '1564519824654'
  alias: Licht in inkom, Keuken, WC (na 5s)  na bewegingsdetectie
  trigger:
  - entity_id: sensor.aeon_labs_zw100_multisensor_6_burglar
    from: '0'
    platform: state
    to: '8'
  condition: []
  action:
  - data:
      entity_id: switch.inkom
    service: switch.turn_on
  - data:
      entity_id: switch.keuken
    service: switch.turn_on
  - delay: 
      seconds: 5
  - data:
      entity_id: switch.WC
    service: switch.turn_on
- id: '1564522772067'
  alias: Licht in inkom uit als meer dan 1 minuut geen beweging
  trigger:
  - entity_id: sensor.aeon_labs_zw100_multisensor_6_burglar
    from: '8'
    platform: state
    to: '0'
  condition: []
  action:
  - data:
      entity_id: switch.inkom
    service: switch.turn_off
- id: '1564952758423'
  alias: AanwezigheidsSimulatie (enkel s'nachts)
  trigger: []
  condition: []
  action:
  - delay: 'seconds: 0'
  - data:
      entity_id: switch.keuken
    service: switch.turn_on
  - delay: 'seconds: 10'
  - data:
      entity_id: switch.slaapkamer
    service: switch.turn_on
- id: '1564956549827'
  alias: Alarm Aangezet (luistert naar vibratie inkom detector)
  trigger:
  - entity_id: sensor.aeon_labs_zw100_multisensor_6_burglar
    from: '0'
    platform: state
    to: '3'
  - entity_id: sensor.aeon_labs_zw100_multisensor_6_burglar
    from: '8'
    platform: state
    to: '3'
  condition: []
  action:
  - data:
      entity_id: script.leds_flash
    service: script.turn_on
