#
# Automation to switch off all lichts at 2 AM
# Uses the group of all lichts and switches
#
- id: "1564517226706"
  alias: Alle lichten uit om 2 uur s'nachts
  trigger:
    - at: 02:00
      platform: time
  condition: []
  action:
    - data:
        entity_id: group.all_lights_switches
      service: homeassistant.turn_off

#
# Licht aan in de slaapkamer als de zon opkomt en radio in keuken aan
# als Jens thuis is !
#
- alias: Licht en radio aan s'morgens (als Jens thuis is)
  trigger:
    platform: sun
    event: sunset
    offset: "-00:00:00"
  condition:
    condition: state
    entity_id: device_tracker.huawei_jens
    state: home
  action:
    - data:
        entity_id: switch.slaapkamer
      service: switch.turn_on
    - data:
        entity_id: media_player.eetkamer
      service: media_player.turn_on

- id: "1564519824654"
  alias: Licht in inkom, Keuken, WC (na 5s)  na bewegingsdetectie
  trigger:
    - entity_id: sensor.aeon_labs_zw100_multisensor_6_burglar
      from: "0"
      platform: state
      to: "8"
  condition: []
  action:
    - data:
        entity_id: switch.inkom
      service: switch.turn_on
    - data:
        entity_id: switch.keuken
      service: switch.turn_on
    - delay:
        seconds: 5
    - data:
        entity_id: switch.WC
      service: switch.turn_on

- alias: Hue Bewegingsdetectie switcht Hue lampen en inkom
  trigger:
    - entity_id: binary_sensor.led_board_sensor_motion
      from: "off"
      platform: state
      to: "on"
  condition: []
  action:
    - data:
        entity_id: switch.inkom
      service: switch.turn_on
    - data:
        entity_id: light.hue_white_lamp_1
      service: light.turn_on
    - delay:
        seconds: 5
    - data:
        entity_id: light.hue_white_lamp_2
      service: light.turn_on

- id: "1564522772067"
  alias: Licht in inkom uit na 1 minuut geen beweging
  trigger:
    - entity_id: sensor.aeon_labs_zw100_multisensor_6_burglar
      from: "8"
      platform: state
      to: "0"
  condition: []
  action:
    - data:
        entity_id: switch.inkom
      service: switch.turn_off

  #
  # Aanwezigheids simulatie welke een aantal lichten achtereenvolgens voor een bepaalde
  # tijd aan en af switcht.
  #
  # Wordt aan-en-afgezet door de automatisatie entity zelf aan en af te switchen
  #
- id: "1564952758423"
  alias: AanwezigheidsSimulatie
  trigger:
    - entity_id: automation.aanwezigheidssimulatie
      from: "off"
      platform: state
      to: "on"
  condition: []
  action:
    - data:
        entity_id: script.presence_simulation
      service: script.turn_on

- alias: AanwezigheidsSimulatie (enkel s'nachts) Afzetten
  trigger:
    - entity_id: automation.aanwezigheidssimulatie
      from: "on"
      platform: state
      to: "off"
  condition: []
  action:
    - data:
        entity_id: script.presence_simulation
      service: script.turn_off

- id: "1564956549827"
  alias: Alarm Aangezet (luistert naar vibratie inkom detector)
  trigger:
    - entity_id: sensor.aeon_labs_zw100_multisensor_6_burglar
      from: "0"
      platform: state
      to: "3"
    - entity_id: sensor.aeon_labs_zw100_multisensor_6_burglar
      from: "8"
      platform: state
      to: "3"
  condition: []
  action:
    - data:
        entity_id: script.leds_flash
      service: script.turn_on
