title: De Domotica Demonstrator
views: 
#  - !include  views/example.yaml
  - !include views/lichtcontrole.yaml
  - !include views/monitoring.yaml
  - !include views/systeemservices.yaml
  - !include views/automatisaties.yaml
 

          
          
        


        
        
